import pandas as pd
import numpy as np

class RetailFeaturePipeline:
    def __init__(self):
        pass

    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        
        # 1. Target Definition (Stockout Occurred)
        if "Demand" in df.columns and "Inventory Level" in df.columns:
            df["Stockout_Occurred"] = (df["Inventory Level"] < df["Demand"]).astype(int)

        # 2. Datetime Features
        df["Date"] = pd.to_datetime(df["Date"])
        df = df.sort_values(by=["Store ID", "Product ID", "Date"]).reset_index(drop=True)
        df["DayOfWeek"] = df["Date"].dt.dayofweek
        df["Month"] = df["Date"].dt.month
        df["Quarter"] = df["Date"].dt.quarter
        df["Is_Weekend"] = df["DayOfWeek"].apply(lambda x: 1 if x >= 5 else 0)

        # 3. Financial & Competitor Pricing Signals
        df["Effective_Price"] = df["Price"] * (1 - df["Discount"] / 100.0)
        df["Price_Diff_Competitor"] = df["Competitor Pricing"] - df["Effective_Price"]
        df["Price_Ratio_Competitor"] = df["Effective_Price"] / (df["Competitor Pricing"] + 1e-5)

        # 4. Inventory Metrics
        df["Inventory_To_Order_Ratio"] = df["Inventory Level"] / (df["Units Ordered"] + 1e-5)
        df["Inventory_To_Sales_Ratio"] = df["Inventory Level"] / (df["Units Sold"] + 1e-5)

        # 5. Lag & Rolling Window Features
        group = df.groupby(["Store ID", "Product ID"])["Units Sold"]
        for lag in [1, 7, 14]:
            df[f"Lag_Sales_{lag}"] = group.shift(lag)
        for window in [7, 14]:
            df[f"Rolling_Mean_Sales_{window}"] = group.transform(lambda x: x.shift(1).rolling(window).mean())
            df[f"Rolling_Std_Sales_{window}"] = group.transform(lambda x: x.shift(1).rolling(window).std()).fillna(0)

        # Fill lag NaNs generated by group shifting
        df = df.dropna().reset_index(drop=True)
        return df