dataset:
  raw_path: "data/raw/sales_data.csv"
  processed_path: "data/processed/featured_data.csv"

model:
  target_col: "Stockout_Occurred"
  test_size: 0.2
  random_state: 42
  model_save_path: "models/stockout_xgboost.pkl"

mlflow:
  experiment_name: "Retail_Stockout_Optimization"
  tracking_uri: "sqlite:///mlflow.db"